runner:
  cppcheck:
    cmd:
      cppcheck --enable=warning,style,performance,portability --std=c++14 --template='{file}:{line}:{column}: { severity }: { message }' ./pkg 2>&1
    errorformat:
        - "%f:%l:%c: %m"
          - "%f:%l: %m"
    level: warning